### ISSUE TITLE
Error when accessing webgu

### ISSUE THREAD

**Issue by ahmaddxb** [linuxserver/docker-doublecommander#10]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Webui to load doublecommander

## Current Behavior
![image](https://user-images.githubusercontent.com/43728586/163668690-5e04071e-bb86-44a6-a7dd-18c9657ca360.png)

## Steps to Reproduce

1.
2.
3.
4.

## Environment

Docker version 20.10.14, build a224086
docker-compose version 1.29.2, build unknown

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**OS:** Ubuntu 20.04.4 LTS
**CPU architecture:** arm64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)
docker-compose
```
  doublecommander:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/doublecommander:latest
    container_name: doublecommander
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $APPDATADIR/doublecommander/config:/config
      #- /:/storage/root:rw
    ports:
      - 3001:3000
    restart: unless-stopped
```

## Docker logs
    today at 12:46:57[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
    today at 12:46:57[s6-init] ensuring user provided files have correct perms...exited 0.
    today at 12:46:57[fix-attrs.d] applying ownership & permissions fixes...
    today at 12:46:57[fix-attrs.d] done.
    today at 12:46:57[cont-init.d] executing container initialization scripts...
    today at 12:46:57[cont-init.d] 01-envfile: executing... 
    today at 12:46:57[cont-init.d] 01-envfile: exited 0.
    today at 12:46:57[cont-init.d] 01-migrations: executing... 
    today at 12:46:57[migrations] started
    today at 12:46:57[migrations] no migrations found
    today at 12:46:57[cont-init.d] 01-migrations: exited 0.
    today at 12:46:57[cont-init.d] 02-tamper-check: executing... 
    today at 12:46:57[cont-init.d] 02-tamper-check: exited 0.
    today at 12:46:57[cont-init.d] 10-adduser: executing... 
    today at 12:46:57
    today at 12:46:57-------------------------------------
    today at 12:46:57          _         ()
    today at 12:46:57         | |  ___   _    __
    today at 12:46:57         | | / __| | |  /  \
    today at 12:46:57         | | \__ \ | | | () |
    today at 12:46:57         |_| |___/ |_|  \__/
    today at 12:46:57
    today at 12:46:57
    today at 12:46:57Brought to you by linuxserver.io
    today at 12:46:57-------------------------------------
    today at 12:46:57
    today at 12:46:57To support LSIO projects visit:
    today at 12:46:57https://www.linuxserver.io/donate/
    today at 12:46:57-------------------------------------
    today at 12:46:57GID/UID
    today at 12:46:57-------------------------------------
    today at 12:46:57
    today at 12:46:57User uid:    1001
    today at 12:46:57User gid:    1001
    today at 12:46:57-------------------------------------
    today at 12:46:57
    today at 12:46:57[cont-init.d] 10-adduser: exited 0.
    today at 12:46:57[cont-init.d] 12-prep_xrdp: executing... 
    today at 12:46:57[cont-init.d] 12-prep_xrdp: exited 0.
    today at 12:46:57[cont-init.d] 13-keygen: executing... 
    today at 12:46:58
    today at 12:46:58Generating 2048 bit rsa key...
    today at 12:46:58
    today at 12:46:58ssl_gen_key_xrdp1 ok
    today at 12:46:58
    today at 12:46:58saving to rsakeys.ini
    today at 12:46:58
    today at 12:46:58..+......+............+.....+....+...+..+.+........+.........+.+..+....+......+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+..............+.+.....+...+.......+......+.....+............+..........+.................+.+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    today at 12:46:58.....+.....+...+...+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+......+...+....+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+...+............+.....+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    today at 12:46:58-----
    today at 12:46:59[cont-init.d] 13-keygen: exited 0.
    today at 12:46:59[cont-init.d] 30-config: executing... 
    today at 12:46:59[cont-init.d] 30-config: exited 1.
    today at 12:46:59[cont-init.d] 50-gid-video: executing... 
    today at 12:46:59[cont-init.d] 50-gid-video: exited 0.
    today at 12:46:59[cont-init.d] 55-autostart-config: executing... 
    today at 12:46:59[cont-init.d] 55-autostart-config: exited 0.
    today at 12:46:59[cont-init.d] 56-openboxcopy: executing... 
    today at 12:46:59[cont-init.d] 56-openboxcopy: exited 1.
    today at 12:46:59[cont-init.d] 90-custom-folders: executing... 
    today at 12:46:59[cont-init.d] 90-custom-folders: exited 0.
    today at 12:46:59[cont-init.d] 99-custom-scripts: executing... 
    today at 12:46:59[custom-init] no custom files found exiting...
    today at 12:46:59[cont-init.d] 99-custom-scripts: exited 0.
    today at 12:46:59[cont-init.d] done.
    today at 12:46:59[services.d] starting services
    today at 12:46:59[guac-init] Auto start not set, application start on login
    today at 12:46:59[services.d] done.
    today at 12:46:59guacd[457]: INFO:	Guacamole proxy daemon (guacd) version 1.1.0 started
    today at 12:46:59guacd[457]: INFO:	Listening on host 0.0.0.0, port 4822
    today at 12:46:59Starting guacamole-lite websocket server
    today at 12:46:59listening on *:3000
    today at 12:47:10[2022-04-16 12:47:10] [Connection 1]  Client connection open
    today at 12:47:10[2022-04-16 12:47:10] [Connection 1]  Opening guacd connection
    today at 12:47:10[2022-04-16 12:47:10] [Connection 1]  guacd connection open
    today at 12:47:10[2022-04-16 12:47:10] [Connection 1]  Selecting connection type: rdp
    today at 12:47:10[2022-04-16 12:47:10] [Connection 1]  Sending opCode: 6.select,3.rdp;
    today at 12:47:10guacd[457]: INFO:	Creating new client for protocol "rdp"
    today at 12:47:10guacd[457]: INFO:	Connection ID is "$ae721973-dfec-47ac-aa04-7e8b01ea0273"
    today at 12:47:10[2022-04-16 12:47:10] [Connection 1]  Sending opCode: 4.size,4.1279,14.1296?undefined,2.96;
    today at 12:47:10[2022-04-16 12:47:10] [Connection 1]  Sending opCode: 5.audio,9.audio/L16;
    today at 12:47:10[2022-04-16 12:47:10] [Connection 1]  Sending opCode: 5.video;
    today at 12:47:10[2022-04-16 12:47:10] [Connection 1]  Sending opCode: 5.image;
    today at 12:47:10[2022-04-16 12:47:10] [Connection 1]  Server sent handshake: 4.args,13.VERSION_1_1_0,8.hostname,4.port,6.domain,8.username,8.password,5.width,6.height,3.dpi,15.initial-program,11.color-depth,13.disable-audio,15.enable-printing,12.printer-name,12.enable-drive,10.drive-name,10.drive-path,17.create-drive-path,7.console,13.console-audio,13.server-layout,8.security,11.ignore-cert,12.disable-auth,10.remote-app,14.remote-app-dir,15.remote-app-args,15.static-channels,11.client-name,16.enable-wallpaper,14.enable-theming,21.enable-font-smoothing,23.enable-full-window-drag,26.enable-desktop-composition,22.enable-menu-animations,22.disable-bitmap-caching,25.disable-offscreen-caching,21.disable-glyph-caching,16.preconnection-id,18.preconnection-blob,8.timezone,14.recording-path,14.recording-name,24.recording-exclude-output,23.recording-exclude-mouse,22.recording-include-keys,21.create-recording-path,13.resize-method,18.enable-audio-input,9.read-only,16.gateway-hostname,12.gateway-port,14.gateway-domain,16.gateway-username,16.gateway-password,17.load-balance-info
    today at 12:47:10[2022-04-16 12:47:10] [Connection 1]  Sending opCode: 7.connect,0.,9.127.0.0.1,4.3389,0.,3.abc,3.abc,4.1279,14.1296?undefined,2.96,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,12.en-us-qwerty,3.any,4.true,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.;
    today at 12:47:10guacd[494]: INFO:	Security mode: Negotiate (ANY)
    today at 12:47:10guacd[494]: INFO:	Resize method: none
    today at 12:47:10guacd[494]: INFO:	User "@fc7b935b-fcdd-4f97-b7ab-247ba7f4e1d5" joined connection "$ae721973-dfec-47ac-aa04-7e8b01ea0273" (1 users now present)
    today at 12:47:10guacd[494]: INFO:	Loading keymap "base"
    today at 12:47:10guacd[494]: INFO:	Loading keymap "en-us-qwerty"
    today at 12:47:12sh: 1: xauth: not found
    today at 12:47:12
    today at 12:47:12X.Org X Server 1.21.1.3
    today at 12:47:12X Protocol Version 11, Revision 0
    today at 12:47:12Current Operating System: Linux ab4dbde97228 5.13.0-1018-oracle #22~20.04.1-Ubuntu SMP Wed Feb 16 09:29:33 UTC 2022 aarch64
    today at 12:47:12Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.13.0-1018-oracle root=LABEL=cloudimg-rootfs ro console=tty1 console=ttyS0 nvme.shutdown_timeout=10 libiscsi.debug_libiscsi_eh=1 crash_kexec_post_notifiers
    today at 12:47:12xorg-server 2:21.1.3-2ubuntu2 (For technical support please see http://www.ubuntu.com/support) 
    today at 12:47:12Current version of pixman: 0.40.0
    today at 12:47:12	Before reporting problems, check http://wiki.x.org
    today at 12:47:12	to make sure that you have the latest version.
    today at 12:47:12Markers: (--) probed, (**) from config file, (==) default setting,
    today at 12:47:12	(++) from command line, (!!) notice, (II) informational,
    today at 12:47:12	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
    today at 12:47:12(++) Log file: ".xorgxrdp.10.log", Time: Sat Apr 16 08:47:12 2022
    today at 12:47:12(++) Using config file: "/etc/X11/xrdp/xorg.conf"
    today at 12:47:12(==) Using system config directory "/usr/share/X11/xorg.conf.d"
    today at 12:47:12xorgxrdpSetup:
    today at 12:47:12xrdpdevSetup:
    today at 12:47:12rdpmousePlug:
    today at 12:47:12rdpkeybPlug:
    today at 12:47:12rdpIdentify:
    today at 12:47:12rdpDriverFunc: op 10
    today at 12:47:12rdpProbe:
    today at 12:47:12rdpProbe: found DRMDevice xorg.conf value [/dev/dri/renderD128]
    today at 12:47:12rdpProbe: found DRI3 xorg.conf value [1]
    today at 12:47:12rdpPreInit:
    today at 12:47:12rdpPreInit: /dev/dri/renderD128 open failed
    today at 12:47:12rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
    today at 12:47:12rdpScreenInit: pfbMemory bytes 1920000
    today at 12:47:12rdpScreenInit: pfbMemory 0xffff9370b010
    today at 12:47:12rdpSimdInit: assigning yuv functions
    today at 12:47:12rdpClientConInit: disconnect idle session after [0] sec
    today at 12:47:12rdpClientConInit: kill disconnected [0] timeout [0] sec
    today at 12:47:12rdpXvInit: depth 24
    today at 12:47:12rdpScreenInit: out
    today at 12:47:12rdpCreateScreenResources:
    today at 12:47:12rdpmousePreInit: drv 0xaaaaeb078bd0 info 0xaaaaeb1e6ef0, flags 0x0
    today at 12:47:12rdpmouseControl: what 0
    today at 12:47:12rdpmouseDeviceInit:
    today at 12:47:12rdpmouseCtrl:
    today at 12:47:12rdpRegisterInputCallback: type 1 proc 0xffff93900c40
    today at 12:47:12rdpmouseControl: what 1
    today at 12:47:12rdpmouseDeviceOn:
    today at 12:47:12rdpkeybPreInit: drv 0xaaaaeb07b620 info 0xaaaaeb3710a0, flags 0x0
    today at 12:47:12rdpkeybControl: what 0
    today at 12:47:12rdpkeybDeviceInit:
    today at 12:47:12rdpkeybChangeKeyboardControl:
    today at 12:47:12rdpkeybChangeKeyboardControl: autoRepeat on
    today at 12:47:12rdpRegisterInputCallback: type 0 proc 0xffff938e1910
    today at 12:47:12rdpkeybControl: what 1
    today at 12:47:12rdpkeybDeviceOn:
    today at 12:47:12rdpDeferredRandR:
    today at 12:47:12rdpResizeSession: width 1024 height 768
    today at 12:47:12  calling RRScreenSizeSet
    today at 12:47:12rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
    today at 12:47:12rdpRRGetInfo:
    today at 12:47:12  screen resized to 1024x768
    today at 12:47:12  RRScreenSizeSet ok 1
    today at 12:47:12rdpResizeSession: width 1276 height 1296
    today at 12:47:12  calling RRScreenSizeSet
    today at 12:47:12rdpRRScreenSetSize: width 1276 height 1296 mmWidth 338 mmHeight 343
    today at 12:47:12rdpRRGetInfo:
    today at 12:47:12  screen resized to 1276x1296
    today at 12:47:12  RRScreenSizeSet ok 1
    today at 12:47:12rdpClientConGotConnection:
    today at 12:47:12rdpClientConGotConnection: g_sck_accept ok new_sck 7
    today at 12:47:12rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
    today at 12:47:12rdpAddClientConToDev: adding first clientCon 0xaaaaeb3aeb00
    today at 12:47:12rdpClientConProcessMsgVersion: version 0 0 0 1
    today at 12:47:12rdpClientConProcessScreenSizeMsg: set width 1276 height 1296 bpp 16
    today at 12:47:12rdpClientConProcessScreenSizeMsg: shmemid 0 shmemptr 0xffff89369000
    today at 12:47:12rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1276 cy 1296
    today at 12:47:12rdpClientConProcessMsgClientInfo:
    today at 12:47:12  got client info bytes 7072
    today at 12:47:12  jpeg support 0
    today at 12:47:12  offscreen support 0
    today at 12:47:12  offscreen size 0
    today at 12:47:12  offscreen entries 0
    today at 12:47:12  client supports glyph cache but server disabled
    today at 12:47:12  client can not do offscreen to offscreen blits
    today at 12:47:12  client can do new(color) cursor
    today at 12:47:12  client can not do multimon
    today at 12:47:12rdpRRSetRdpOutputs: numCrtcs 0 numOutputs 0 monitorCount 0
    today at 12:47:12rdpRRSetRdpOutputs: add output 0 left 0 top 0 width 1276 height 1296
    today at 12:47:12rdpLoadLayout: keylayout 0x00000409 variant  display 10
    today at 12:47:12rdpkeybChangeKeyboardControl:
    today at 12:47:12rdpkeybChangeKeyboardControl: autoRepeat on
    today at 12:47:12rdpkeybChangeKeyboardControl:
    today at 12:47:12rdpkeybChangeKeyboardControl: autoRepeat on
    today at 12:47:12(EE) Failed to open authorization file ".Xauthority": No such file or directory
    today at 12:47:12rdpInDeferredRepeatCallback:
    today at 12:47:12rdpkeybChangeKeyboardControl:
    today at 12:47:12rdpkeybChangeKeyboardControl: autoRepeat off
    today at 12:47:12guacd[494]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
    today at 12:47:12guacd[494]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
    today at 12:47:12guacd[494]: INFO:	Connected to RDPDR 1.12 as client 0xe357447d
    today at 12:47:12guacd[494]: INFO:	RDPDR user logged on
    today at 12:47:12rdpInDeferredRepeatCallback:
    today at 12:47:12rdpkeybChangeKeyboardControl:
    today at 12:47:12rdpkeybChangeKeyboardControl: autoRepeat off
    today at 12:47:12rdpInDeferredRepeatCallback:
    today at 12:47:12rdpkeybChangeKeyboardControl:
    today at 12:47:12rdpkeybChangeKeyboardControl: autoRepeat off

**Comment by m33ts4k0z** [comment]
The same issue happens for me. It can be that this only occurs in headless systems.

**Comment by Ibbanez** [comment]
This is also happening on my UnRaid server once I updated to 6.10.1.  This is the only Docker that is having this issue.  I even removed it, deleted the original folder out of the appdata folder, and it is still happening after reinstalling.  So I'm not sure what the issue is.  This is my favorite file manager on my UnRaid Server, so I hope this can be figured out. I was thinking it was a permission issue, but I honestly don't know enough to make that a definitive answer.  Any help would be welcome.  Thanks.

**Comment by m33ts4k0z** [comment]
@ahmaddxb I had the same problem running this container from Unraid. What I needed to do is to toggle the container as privileged. That solved the issue for me.

**Comment by m33ts4k0z** [comment]
> This is also happening on my UnRaid server once I updated to 6.10.1. This is the only Docker that is having this issue. I even removed it, deleted the original folder out of the appdata folder, and it is still happening after reinstalling. So I'm not sure what the issue is. This is my favorite file manager on my UnRaid Server, so I hope this can be figured out. I was thinking it was a permission issue, but I honestly don't know enough to make that a definitive answer. Any help would be welcome. Thanks.

 I had the same problem running this container from Unraid. What I needed to do is to toggle the container as privileged. That solved the issue for me.

**Comment by Ibbanez** [comment]
> o

That fixed it for me, thanks.  The only one I couldn't get was DoubleCommander, but this fixed it right up.  Thanks.  Any thoughts as to why updating would do this? I never had this problem before.

**Comment by ahmaddxb** [comment]
Ok thanks I will give it a try, hopefully that solves it for me too.

Edit: It is working now running with privileged: true

**Comment by flipphos** [comment]
Setting privileged: true worked for me on unRAID 6.11.3 as well.
