### ISSUE TITLE
[BUG] Blank black screen after KASM rebase

### ISSUE THREAD

**Issue by jokob-sk** [linuxserver/docker-doublecommander#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Blank black screen after KASM rebase

### Steps To Reproduce

1. Blank black screen after KASM rebase
2. Downgrade to `linuxserver/doublecommander:544a132d-ls144` > this image works

### Environment

```markdown
- OS: Synology
- How docker service was installed: docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3"
services:
  doublecommander:
    container_name: doublecommander
    image: "linuxserver/doublecommander"
    network_mode: "bridge"
    restart: always
    ports:
      - "3000:3000" # host:container
    volumes:
      - ${BACKUP_LOCATION}:/mnt/Backup   # persistent/host/path:container/path
      - ${PLEX_LOCATION}:/mnt/Plex
      - ${SYNCTHING_LOCATION}:/mnt/Syncthing
      - ${SHARED_LOCATION}:/mnt/Shared
      - ${BACKUP_LOCATION}/x_local/soft/favicons/totalcmd/favicon.ico:/gclient/public/favicon.ico
      - ${BACKUP_LOCATION}/x_local/soft/favicons/totalcmd/ms-icon-70x70.png:/gclient/public/icon.png      
      - ${FUN_DATA_LOCATION}:/mnt/usbshare2
      - ${APP_DATA_LOCATION}/doublecommander:/config
```

### Container logs

```bash
...
```

**Comment by thelamer** [comment]
Can you please test the latest image and let me know if this is still occurring.

**Comment by jokob-sk** [comment]
Hey,

Still the same issue persists:

```

doublecommander    | [migrations] started
doublecommander    | [migrations] no migrations found
doublecommander    | ───────────────────────────────────────
doublecommander    |
doublecommander    |       ██╗     ███████╗██╗ ██████╗
doublecommander    |       ██║     ██╔════╝██║██╔═══██╗
doublecommander    |       ██║     ███████╗██║██║   ██║
doublecommander    |       ██║     ╚════██║██║██║   ██║
doublecommander    |       ███████╗███████║██║╚██████╔╝
doublecommander    |       ╚══════╝╚══════╝╚═╝ ╚═════╝
doublecommander    |
doublecommander    |    Brought to you by linuxserver.io
doublecommander    | ───────────────────────────────────────
doublecommander    |
doublecommander    | To support LSIO projects visit:
doublecommander    | https://www.linuxserver.io/donate/
doublecommander    |
doublecommander    | ───────────────────────────────────────
doublecommander    | GID/UID
doublecommander    | ───────────────────────────────────────
doublecommander    |
doublecommander    | User UID:    1029
doublecommander    | User GID:    911
doublecommander    | ───────────────────────────────────────
doublecommander    |
doublecommander    | [custom-init] No custom files found, skipping...
doublecommander    | [ls.io-init] done.
doublecommander    | _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
doublecommander    |
doublecommander    | Xvnc KasmVNC 1.1.0 - built Apr  8 2023 21:33:54
doublecommander    | Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
doublecommander    | See http://kasmweb.com for information on KasmVNC.
doublecommander    | Underlying X server release 12014000, The X.Org Foundation
doublecommander    |
doublecommander    | Obt-Message: Xinerama extension is not present on the server
doublecommander    |
doublecommander    | ERROR: openbox-xdg-autostart requires PyXDG to be installed
doublecommander    |  2023-04-09 09:53:33,905 [INFO] websocket 0: got client connection from 127.0.0.1
doublecommander    |  2023-04-09 09:53:33,918 [PRIO] Connections: accepted: @172.17.0.1_1680998013.905688::websocket
doublecommander    |  2023-04-09 09:53:37,090 [PRIO] Connections: closed: @172.17.0.1_1680998013.905688::websocket (Clean disconnection)
doublecommander    |  2023-04-09 09:53:37,585 [INFO] websocket 1: got client connection from 127.0.0.1
doublecommander    |  2023-04-09 09:53:37,599 [PRIO] Connections: accepted: @172.17.0.1_1680998017.586189::websocket
```

![image](https://user-images.githubusercontent.com/96159884/230747342-cc39ba54-fe56-4fa0-ab9a-c9ed8f8860f1.png)

**Comment by thelamer** [comment]
Right click the desktop, select xterm and type in `doublecmd`

**Comment by thelamer** [comment]
Also what is the runc version on synology these days. 
This rebase brings Alpine 3.17 as well seccomp unconfined can only do so much if it is an ancient kernel/libseccomp.

`runc --version` from the CLI of the host

**Comment by jokob-sk** [comment]
This works:  Right click the desktop, select xterm and type in `doublecmd`

FYI as requested:

```
runc --version
runc version v1.0.0-rc93
commit: 31cc25f16f5eba4d0f53e35374532873744f4b31
spec: 1.0.2-dev
go: go1.17.1

```

**Comment by thelamer** [comment]
Ok so new image is pushed, autostart works on every distro I tested, went all the way back to bullseye. I don't have a Synology to test on but that is an old version of Docker/Runc, what version of syno is this? As we continually upgrade the OS and stuff in the containers eventually something will break against the host as desktop applications make syscalls that stuff like nginx and cli apps simply do not. It is kind of a different world of compatibility where you gotta at least be running an LTS kernel from the last 4 years and a couple versions back of libseccomp. 
https://ci-tests.linuxserver.io/linuxserver/doublecommander/cad11ef8-ls146/index.html

**Comment by jokob-sk** [comment]
Downloaded the image and getting this:

```
doublecommander    | ───────────────────────────────────────
doublecommander    |
doublecommander    | [custom-init] No custom files found, skipping...
doublecommander    | [ls.io-init] done.
doublecommander    | _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
doublecommander    |
doublecommander    | Xvnc KasmVNC 1.1.0 - built Apr  9 2023 00:38:52
doublecommander    | Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
doublecommander    | See http://kasmweb.com for information on KasmVNC.
doublecommander    | Underlying X server release 12014000, The X.Org Foundation
doublecommander    |
doublecommander    | Obt-Message: Xinerama extension is not present on the server
doublecommander    |
doublecommander    | ERROR: openbox-xdg-autostart requires PyXDG to be installed
doublecommander    |  2023-04-09 11:44:24,317 [INFO] websocket 0: got client connection from 127.0.0.1


```

- it's the latest version "Version: 7.1.1-42962 Update 4 "

>  As we continually upgrade the OS and stuff in the containers eventually something will break against the host 

Yep, fully understand.


I feel a little bit of regret 😣not building my own NAS and having more control over the box, but well, what can you do now. The next build would be a custom NAS so the underlying system would be in my full control. 

Something however to consider is that a lot of people start off on e.g. a Synology so some kind of limited support would probably help the adoption of images. Not sure if you can pull stats on where your images are running, just an idea to consider.

**Comment by thelamer** [comment]
All of those messages are normal. You should still be able to connect to the container and get some kind of desktop.
Also just in general these app container have right click links to launch the app as well not sure if the terminal is 100% required. Might just have to be something to deal with until you can upgrade your software somehow.
Also another option would be to spin up a webtop and install everything you use in it and stop using us for upgrades. Something like alpine-icewm will be just as lean as openbox and you can apk install most apps having a similar to windows experience.
https://github.com/linuxserver/docker-webtop
In fact one webtop with many apps will use significantly less ram than many app containers. Just an idea.

Leave it running and stop managing upgrades with docker, just use apk whenever you feel like it.

**Comment by jokob-sk** [comment]
Thanks for the support.

I'm already running webtop so combining them seems like a good idea. Will give it a think.

Cheers

**Comment by masterwishx** [comment]
Also have this issue with dcommander and webtop using Ubuntu 20.4.1 in Oracle cloud
