### ISSUE TITLE
[FEAT] Rsync in the docker

### ISSUE THREAD

**Issue by djmulder** [linuxserver/docker-doublecommander#18]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hey there,

I just have a simple request: can rsync be added to this docker image? 

### Reason for change

Double commander has a terminal window (F9). You have a few more options with rsync for larger transfers

### Proposed code change

Change: 
  apt-get install -y \
    doublecmd-gtk \
    doublecmd-plugins \
    libsmbclient \
    libssh2-1 && \

into

  apt-get install -y \
    doublecmd-gtk \
    doublecmd-plugins \
    libsmbclient \
    libssh2-1 \
    rsync && \

**Comment by Roxedus** [comment]
You can use a mod to have the container install rsync on rebuild. 
https://github.com/linuxserver/docker-mods/tree/universal-package-install
