### ISSUE TITLE
[FEAT] Working with rar archives

### ISSUE THREAD

**Issue by LightTemplar** [linuxserver/docker-doublecommander#21]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like to extract .rar archives with Double Commander. 

### Reason for change

I have unextracted .rar archives under my old downloads and I would like work with them.

### Proposed code change

For now it asks for `libunrar.so`, but I don't know, if it will need more libraries.

**Comment by LightTemplar** [comment]
<imitating activity, so the feature request won't get closed>

**Comment by thelamer** [comment]
https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by LightTemplar** [comment]
Solved, thanks to: https://github.com/linuxserver/docker-doublecommander/pull/22
I tested, it works!
