### ISSUE TITLE
Add variable to choose a different user than abc

### ISSUE THREAD

**Issue by fl0wfr** [linuxserver/docker-doublecommander#6]
Hi,

Would it be possible to add a variable to choose a different user than abc? I have protected the user with a password but I've also tried to usermod abc to rename it to another username but when I restart the container I get this error:
`s6-envuidgid: fatal: unknown user: abc`

Thanks!
Best regards,

**Comment by aptalca** [comment]
We don't support that as too many things are hardcoded to abc in our init scripts and services
